config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin/dashboard#index'
  namespace :admin do
    resources :pages, :courses, :tags
    resources :pages do
      resources :courses do
      end
    end
  end
  get 'dashboard/coursesedit'
  get 'welcome/index'

  resources :pages do
    resources :courses do
    end
  end

  root 'pages#index'

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :integer          not null, primary key
#  Name       :string
#  page_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :text
#

class Course < ActiveRecord::Base
  belongs_to :page
  has_many :tag_assigments
  has_many :tags, through: :tag_assigments
  validates :Name, presence: true
  validates :body, presence: false
  validates_associated :tags
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  visible    :boolean
#

class Page < ActiveRecord::Base
  has_many :courses
  before_save :default_values
  validates :title, presence: true,
                    length: {minimum: 5}
  validates :visible, presence: false
  before_save :default_values
  validates_associated :courses
  validates :visible, inclusion: { in: ["0", "1"] }


  def default_values
    if self.text == ""
    self.text = "Default text = insert a content."
    end

  end
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
 has_many :tag_assigments
  has_many :courses, through: :tag_assigments
  validates :name, presence: true
  validates :text, presence: false
end

app/models/tag_assigment.rb
# == Schema Information
#
# Table name: tag_assigments
#
#  id         :integer          not null, primary key
#  tag_id     :integer
#  course_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TagAssigment < ActiveRecord::Base
  belongs_to :tag
  belongs_to :course
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  def index
    @pages = Page.all
    @courses = Course.all
  end
  def show
    @course = Course.find(params[:id])
  end
  def new
    @page = Page.find(params[:page_id])
    @course = @page.courses.new
  end
  def edit
    @page = Page.find(params[:page_id])
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @page = Page.find(params[:page_id])
    if @course.update(course_params)
      redirect_to admin_courses_path
    else
      render 'edit'
    end
  end

  def create
    @page = Page.find(params[:page_id])
    @course = @page.courses.create(course_params)
    if @course.save
      redirect_to admin_courses_path
    else
      render 'new'
    end
  end
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to admin_courses_path
  end

  private
  def course_params
    params.require(:course).permit(:Name, :body, :page_id, :tag_ids => [])
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  def index
    @pages = Page.all
    @courses = Course.all
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  def index
    @pages = Page.all
  end
  def admin
    @pages = Page.all
  end
  def show
    @page = Page.find(params[:id])
  end
  def new
    @page = Page.new
  end
  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to admin_pages_path
    else
      render 'edit'
    end
  end

  def create
    @page = Page.new(page_params)
    if @page.save
    redirect_to admin_pages_path
    else
      render 'new'
    end
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to admin_pages_path
  end
  private
  def page_params
    params.require(:page).permit(:title, :text, :visible)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin"
  def index
    @tag = Tag.new
    @tags = Tag.all
  end


  def new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      if params[:tag][:page_id] != ""
        redirect_to edit_admin_page_course_path(params[:tag][:page_id], params[:tag][:course_id])
      elsif params[:tag][:page_id] != ""
        redirect_to new_admin_page_course_path(params[:tag][:page_id])
        else
          redirect_to admin_courses_path
      end

    else
      render 'admin/courses/new'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to :back
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
  def show
    @course = Course.find(params[:id])
  end

  private
  def course_params
    params.require(:course).permit(:Name, :tag_ids => [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end
  def show

    @page = Page.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_visible_pages
    return @pages_menu = Page.where(:visible => 1)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_header.html.erb
<header>
  <h1>one2one - edukační platforma.</h1>
</header>

app/views/admin/_menu.html.erb
<%= render 'admin/header' %>
<aside>
  <nav>
    <%= link_to "Dashboard", admin_path %>
    <%= link_to "Pages", admin_pages_path %>
    <%= link_to "Courses", admin_courses_path %>

  </nav>
</aside>

app/views/admin/courses/_form.html.erb
<%= simple_form_for([:admin,@page, @course]) do |f| %>
    <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@course.errors.count, "error") %> prohibited
            this course from being saved:
          </h2>
          <ul>
            <% @course.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :Name %><br>
      <%= f.text_field :Name %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>

    <div class="field"></div>
      <%= f.association :page %>
    </p>
    <%= f.label :tag %>
      <%= f.association :tags, as: :check_boxes %>
    <%= link_to 'Add/Edit Tags', new_admin_tag_path(page_id:@page, course_id:@course) %>




    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/admin/courses/edit.html.erb
<%= render 'admin/menu' %>
<section>
<%= render 'form' %>
</section>

app/views/admin/courses/index.html.erb
<%= render 'admin/menu' %>
<section>
<h1 style="">Courses</h1>

    <% @pages.each do |page| %>
      <div class="row rec rec-big">
      <table>
        <tr>
          <h2 style="float: left;"><%= page.title %></h2>
        </tr>


        <tr>
          <th>Course:</th>
          <th>Created at:</th>
          <th>Updated at:</th>
          <th>Actions:</th>
        </tr>
          <% page.courses.each do |course| %>

         <tr>
          <td><%= course.Name %></td>

              <td><small><%= course.created_at %></small></td>
              <td><small><%= course.updated_at %></small></td>
          <td><%= link_to 'Show', page_course_path(page,course) %></td>
          <td><%= link_to 'Edit', edit_admin_page_course_path(page,course) %></td>
          <td><%= link_to 'Delete', admin_course_path(course), method: :delete, data: { confirm: "Sure?"} %></td>
          </tr>
        <% end %>
      </table>
        <br>
       <%= link_to 'Create a New Course', new_admin_page_course_path(page) %>
      </div>
  <% end %>
</section>

app/views/admin/courses/new.html.erb
<%= render 'admin/menu' %>
<section>
<%= render 'form' %>
</section>

app/views/admin/dashboard/index.html.erb
<%= render 'admin/menu' %>
<section>
  <div class="row">
      <a href="<%= admin_pages_path %>">
      <div class="circle">
        <h2>Pages (<%= Page.all.count %>)</h2>
      </div>
      </a>
    <a href="<%= admin_courses_path %>">
      <div class="circle">
        <h2>Courses (<%= @courses.count %>)</h2>

      </div>
    </a>

  </div>
</section>

app/views/admin/pages/_form.html.erb
<%= simple_form_for [:admin,@page] do |f| %>
    <% if @page.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@page.errors.count, "error") %> prohibited
            this page from being saved:
          </h2>
          <ul>
            <% @page.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :visible %><br>
      <%= f.check_box :visible %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/admin/pages/edit.html.erb
<%= render 'admin/menu' %>

<section>
<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>
</section>

app/views/admin/pages/index.html.erb
<%= render 'admin/menu' %>
<section>
  <h1 style="">Pages</h1>
  <div class="rec rec-big">


  <table>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Visibility</th>
      <th>Created at</th>
      <th>Updated at</th>
    </tr>

    <% @pages.each do |page| %>
        <tr>
          <td><%= page.title %></td>
          <td><%= page.text.first(30) %></td>
          <td><%= page.visible == 1 ? "visible" : "hidden" %></td>
          <td><small><%= page.created_at %></small></td>
          <td><small><%= page.updated_at %></small></td>
          <td><%= link_to 'Show', page_path(page) %></td>
          <td><%= link_to 'Edit', edit_admin_page_path(page) %></td>
          <td><%= link_to 'Delete', admin_page_path(page), method: :delete, data: { confirm: "Sure?"} %></td>

        </tr>

    <% end %>
    </table>
    <%= link_to 'Create New page', new_admin_page_path %>

  </div>

</section>

app/views/admin/pages/new.html.erb
<%= render 'admin/menu' %>
<section>
<%= render 'form' %>

<%= link_to 'back', pages_path %>
</section>

app/views/admin/pages/show.html.erb
<%= render 'layouts/menu' %>
<section>
  <div class="row">
    <div class="rec rec-big">
      <article>
        <h2><%= @page.title %></h2>
        <p> <%= @page.text %>

        </p>
        <%= link_to 'Edit', edit_page_path(@page) %>
      </article>
    </div>
  </div>
  <div class="row">
    <% @page.courses.each do |course| %>
        <div class="col">

          <div class="circle">
            <h2>
              <%= link_to course.Name, page_course_path(@page, course) %>
            </h2>
          </div>
        </div>

    <% end %>




  </div>
</section>

app/views/admin/tags/_form.html.erb
<%= simple_form_for([:admin,@tag]) do |f| %>
    <%= f.hidden_field :page_id, :value => params[:page_id] %>
    <%= f.hidden_field :course_id, :value => params[:course_id] %>

    <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tag.errors.count, "error") %> prohibited
            this tag from being saved:
          </h2>
          <ul>
            <% @tag.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/admin/tags/new.html.erb
<%= render 'admin/menu' %>
<section>
  <div class="row rec-big" style="text-align: left;">
  <table>

  <% @tags.each do |tag| %>
        <tr><td><%= tag.name %> <%= link_to 'delete', admin_tag_path(tag), method: :delete, data: { confirm: 'Sure?'}  %></td></tr>
    <% end %>

  </table>
  </div>
  <h1>Add a New Tag</h1>
  <%= render 'form' %>
</section>

app/views/courses/show.html.erb
<%= render 'layouts/menu' %>
<section>
  <div class="row">
    <div class="rec rec-big">
      <article>
        <h1><%= @course.Name %></h1>
        <p>
          <%= @course.body %>
          <% if @course.tags.any? %>
            <div class="tags">
            <h3>Tags:</h3>
            <ul>
              <% @course.tags.each do |tag| %>
                  <li><%= tag.name %></li>
              <% end %>
            </ul>
            </div>
        <% end %>
        </p>
      </article>
    </div>
  </div>
</section>

app/views/layouts/_header.html.erb
<header>
  <h1>one2one - edukační platforma.</h1>
</header>

app/views/layouts/_menu.html.erb
<%= render 'layouts/header' %>
<aside>
  <img src="/logo.png" alt="Omentoro logo">
  <nav>
    <%= link_to "Domu", root_url %>
    <% get_visible_pages.each do |page| %>

        <%= link_to page.title, page_path(page), class: ('active' if request.path == page_path(page))%>

    <% end %>
  </nav>

  <%= link_to 'Admin', admin_path, class: "dashboard" %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omentoro </title>
  <link href="https://fonts.googleapis.com/css?family=Varela" rel="stylesheet">
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<%= render 'layouts/menu' %>
<section>
  <div class="row">
    <div class="rec rec-big">
      <article>
        <h2>Omentoro</h2>
        <p>Služba Omentoro poskytuje dobré zázemí v předávání znalostí a jejich získávání. Nabízí sledování
          tvého postupu v lekcích mentory, ti ho vyhodnotí a zodpoví dotazy pří online či face2face
          konzultacích.
          <!--<img src="./img/28102-NWXVXP.jpg"> -->
        </p>
      </article>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="circle">

        <img src="/img/9_learning-01.jpg" alt="Learn">
      </div>

      <div class="rec rec-below-circle">
        <h3>Nauč se a získej XP pointy</h3>
        <p>Výklad je přehledně sktrukturován, doplněn průběžné znalostní kvízy a ty porovnávej. To vše bude aby.
          aby učení bylo hrou a novou výzvou.</p>
      </div>
    </div>
    <div class="col">
      <div class="circle">
        <img src="/img/idea08.jpg" alt="Create">
      </div>
      <div class="rec rec-below-circle">
        <h3>Vytvářej</h3>
        <p>Staň se i ty součástí obsahu. A předej své zkušenosti ostatním. Mentoruj, a sleduj postup svých
          studentů.
        </p>
      </div>
    </div>
    <div class="col">
      <div class="circle">
        <img src="/img/7_150.jpg" alt="Share">
      </div>
      <div class="rec rec-below-circle">
        <h3>Sdílej se</h3>
        <p>Sdílej svoji zkušenost se svým mentorem, nebo všichni mentoři mezi sebou.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="rec rec-small" style="display: block;">
      <p><strong>Zůstaň ve spojení</strong></p>
    </div>
  </div>
  <div class="row  row-bottom">

    <div class="circle">
      <a href="/pridej-se.html">
        <h2 class="active">Přidej se</h2>
      </a>
    </div>
    <div class="circle">
      <a href="#">
        <h2>Facebook</h2>
      </a>
    </div>
    <div class="circle">
      <a href="/omentoro-metoda.html">
        <h2>Naše metoda</h2>
      </a>
    </div>
  </div>
</section>

app/views/pages/show.html.erb
<%= render 'layouts/menu' %>
<section>
  <div class="row">
    <div class="rec rec-big">
      <article>
        <h2><%= @page.title %></h2>
        <p> <%= @page.text %>

        </p>
        <%= link_to 'Edit', edit_admin_page_path(@page) %>
      </article>
    </div>
  </div>
  <div class="row">
    <% @page.courses.each do |course| %>
        <div class="col">

          <div class="circle">
            <h2>
              <%= link_to course.Name, page_course_path(@page, course) %>
            </h2>
          </div>
        </div>

    <% end %>


  </div>
</section>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Pages', controller: 'pages' %>